# apiVersion: v1
# kind: Service
# metadata:
#   name: product-service
# spec:
#   type: NodePort
#   selector:
#     app: product-service
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5566
#       nodePort: 30002

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: LoadBalancer
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5566
