# apiVersion: v1
# kind: Service
# metadata:
#   name: customer-service
# spec:
#   type: NodePort
#   selector:
#     app: customer-service
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 6655
#       nodePort: 30001


apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: LoadBalancer
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6655
